# ------------------------------------------------------------------
# Application Configuration
# http://code.google.com/appengine/docs/python/config/appconfig.html
# ==================================================================
# vim:ft=yaml fdm=marker

application: academiamongolica-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: true

# time a static file cache by user's browser
default_expiration: "365d"

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: django
  version: latest

# Built-in modules {{{1
builtins:
- appstats: on
# admin_redirect, appstats, default, deferred, django_wsgi, remote_api

# Handlers {{{1
handlers:
- url: /static
  static_dir: static
  expiration: "365d"

- url: /favicon\.ico
  static_files: static/ico/favicon.ico
  upload: static/ico/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: vendor.choppy.boot.application

# Skipped (ignored) files {{{1
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?.*\.bak$
  - ^(.*/)?.*\.less$

# inbound_services: # - xmpp_message, - mail

# Error handlers {{{1
# TODO: test and confirm this feature
error_handlers:
- file: vendor/choppy/bundle/core/error_handlers/default_error.html

# over quota
- error_code: over_quota
  file: vendor/choppy/bundle/core/error_handlers/over_quota.html

# dos api denial
- error_code: dos_api_denial
  file: vendor/choppy/bundle/core/error_handlers/dos_api_denial.html

# timeout
- error_code: timeout
  file: vendor/choppy/bundle/core/error_handlers/timeout.html
